### ISSUE TITLE
problem with package dependency

### ISSUE THREAD

**Issue by matt74** [CardioKit/PeakWatch#31]
Hello, I tried your sample code but I have issue with peakswift package dependency. See the screenshot. I have an error when I want to add it to the project. I'm using latest Xcode 15.0

<img width="1079" alt="Capture d’écran 2023-10-19 à 12 03 17" src="https://github.com/CardioKit/PeakWatch/assets/314022/bfabd3cd-9e31-47f1-a0fe-fad22e70a6ab">

**Comment by NumericalMax** [comment]
Hi Matthias, thank you for bringing this issue to our attention. We have now changed how the PeakSwift package fetches submodules, i.e., using https instead of ssh. May you check whether the package includes the submodules correctly and PeakWatch compiles. Best Max

**Comment by matt74** [comment]
Thanks for the fix. It's working well now.
